#!/bin/bash

calendar() {
LOCK_FILE="~/.cache/eww-calendar.lock"
EWW_BIN="eww"

run() {
    eww -c ~/.config/eww/bar open calendar
}

# Open widgets
if [[ ! -f ~/.cache/eww-calendar.lock ]]; then
    eww -c ~/.config/eww/bar close system music_win audio_ctl
    touch ~/.cache/eww-calendar.lock
    run && echo "ok good!"
else
    eww -c ~/.config/eww/bar close calendar
    rm ~/.cache/eww-calendar.lock && echo "closed"
fi
}


system() {
LOCK_FILE_MEM="~/.cache/eww-system.lock"
EWW_BIN="eww"

run() {
    eww -c ~/.config/eww/bar open system 
}

# Open widgets
if [[ ! -f ~/.cache/eww-system.lock ]]; then
    eww -c ~/.config/eww/bar close calendar music_win audio_ctl
    touch ~/.cache/eww-system.lock
    run && echo "ok good!"
else
    eww -c ~/.config/eww/bar close system 
    rm ~/.cache/eww-system.lock && echo "closed"
fi
}


music() {
LOCK_FILE_SONG="~/.cache/eww-song.lock"
EWW_BIN="eww"

run() {
    eww -c ~/.config/eww/bar open music_win 
}

# Open widgets
if [[ ! -f ~/.cache/eww-song.lock ]]; then
    eww -c ~/.config/eww/bar close system calendar
    touch ~/.cache/eww-song.lock
    run && echo "ok good!"
else
    eww -c ~/.config/eww/bar close music_win
    rm ~/.cache/eww-song.lock && echo "closed"
fi
}



audio() {
LOCK_FILE_AUDIO="~/.cache/eww-audio.lock"
EWW_BIN="eww"

run() {
    eww -c ~/.config/eww/bar open audio_ctl 
}

# Open widgets
if [[ ! -f ~/.cache/eww-audio.lock ]]; then
    eww -c ~/.config/eww/bar close system calendar music
    touch ~/.cache/eww-audio.lock
    run && echo "ok good!"
else
    eww -c ~/.config/eww/bar close audio_ctl
    rm ~/.cache/eww-audio.lock && echo "closed"
fi
}

echo "$1"
if [ "$1" = "calendar" ]; then
calendar
elif [ "$1" = "system" ]; then
system
elif [ "$1" = "music" ]; then
music
elif [ "$1" = "audio" ]; then
audio
fi
