require("config.treesitter")
-- require("config.fugitive")
-- require("config.nvim-tree")
require("config.mason")
require("config.lsp")
require("config.nvim-cmp")
require("config.null-ls")
require("config.lspsaga")
require("config.neotest")
require("config.dap")
-- require("config.tmux")
-- require("config.comment")
-- require("config.colorizer")
-- require("config.surround")
-- require("config.autopairs")
require("config.navic")
-- require("config.gitsigns")
require("config.lualine")
-- require("config.colorscheme")
require("config.telescope")
-- require("config.other")
-- require("config.nvim-notify")
-- require("config.alpha")
-- require("config.impatient")
require("config.neorg")
